bump_version: null
lint: null
nf_core_version: 3.0.0
org_path: null
repository_type: pipeline
template:
  author: Alexander Peltzer
  description: A simple sysops pipeline that can be used to synchronize, integrity
    check and permanently archive data.
  force: false
  is_nfcore: true
  name: datasync
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0dev
update: null
